### ISSUE TITLE
s3 PolicyDocument

### ISSUE THREAD

**Issue by luke-infersens** [stanb/Comformation#12]
Hi,

Many thanks for this project, it's already proving to be very useful.

May I ask for help with regard to converting the below YML to Comformation code, please?

I'm stuck on how exactly I should be using the Union object for the PolicyDocument.

Many thanks,

Luke.

`
    
    DeployBucketPolicy: 

    Type: AWS::S3::BucketPolicy

    Properties: 

    Bucket: !Ref DeployBucket

    PolicyDocument: 

      Statement: 

        - 

          Sid: PublicReadGetObject

          Effect: Allow

          Principal: "*"

          Action: 

            - s3:GetObject            

          Resource: !Join [ "", [ "arn:aws:s3:::", !Ref DeployBucket, "/*" ] ]
`

**Comment by stanb** [comment]
Hi,
Thank you for your positive feedback :)
[Policy document](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-policy.html
) is a JSON. So you can combine json string and parse it with JToken.Parse().
To work with IAM policies you can create Amazon.Auth.AccessControlPolicy.Policy object from AWSSDK.Core, cast it to json string and wrap it with JToken.Parse method.
Something like this:
``` csharp
using Comformation;
using Comformation.IntrinsicFunctions;
using Comformation.S3.BucketPolicy;
using Newtonsoft.Json.Linq;
using Amazon.Auth.AccessControlPolicy;

...
var template = new Template
{
    Resources = new Resources
    {
        ...
        new BucketPolicyResource
        {
            LogicalId = "DeployBucketPolicy",
            Properties =
            {
                Bucket = Fn.Ref("DeployBucket"),
                PolicyDocument = JToken.Parse(new Policy {
                    Version = "2012-10-17",
                    Statements =
                    {
                        new Statement(Statement.StatementEffect.Allow)
                        {
                            Id = "PublicReadGetObject",
                            Principals = { new Principal("*") },
                            Actions = { new ActionIdentifier("s3:GetObject") },
                            Resources = 
                            {
                                new Resource(
                                    Fn.Join("", new List<Union<string, IntrinsicFunction>>
                                    {
                                        "arn:aws:s3:::", Fn.Ref("DeployBucket"), "/*"
                                    }).ToString())
                            }
                        }
                    }
                }.ToJson())
            }
        }
    }
};

```

**Comment by luke-infersens** [comment]
That's great stanb; Thanks very much for taking the time to answer.
